### ISSUE TITLE
Because every version of flutter_test from sdk depends on xml 3.6.1 and excel >=1.0.4 depends on xml ^4.1.0, flutter_test from sdk is incompatible with excel >=1.0.4.

### ISSUE THREAD

**Issue by victor337** [kawal7415/excel#36]
Hi! great package, but I have trouble installing.

after running pub get:
"Since all versions of sdk's flutter_test depend on xml 3.6.1 and excel> = 1.0.4 depend on xml ^ 4.1.0, sdk's flutter_test is incompatible with excel> = 1.0. 4."

I need version 1.0.9, but I have to use 1.0.3 to work
![Screenshot_3](https://user-images.githubusercontent.com/57425547/85643201-ce77cb00-b669-11ea-801c-d43f0f3a1c86.png)

**Comment by kawal7415** [comment]
Similar issues have been solved in the past : https://github.com/kawal7415/excel/issues/26 , https://github.com/kawal7415/excel/issues/25,  https://github.com/kawal7415/excel/issues/11

I hope it helps.

**Comment by apoleo88** [comment]
Tried the solutions suggested and it does not fix the problem, instead, it generates more errors with other libraries.
